services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - casacraft-network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/casacraft
    depends_on:
      - mongo
    networks:
      - casacraft-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - casacraft-network

networks:
  casacraft-network:

volumes:
  mongo-data: